services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HOST=db
      - USER=postgres
      - PASSWORD=postgres
      - DB_NAME=mydatabase
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: